// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import dashboardblocks "github.com/fastygo/blocks/dashboard"

func ContactsPage(data ContactsPageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = dashboardblocks.Contacts(dashboardblocks.ContactsProps{
			Title:            data.PageTitle,
			Description:      data.Description,
			AddTitle:         data.AddHeader,
			Fields:           contactFields(data),
			SubmitLabel:      data.AddButtonText,
			ListTitle:        data.ExistingContactsText,
			EmptyText:        data.NoContactsText,
			NameHeader:       data.NameHeader,
			EmailHeader:      data.EmailHeader,
			CompanyHeader:    data.CompanyHeader,
			CreatedHeader:    data.CreatedHeader,
			DeleteLabel:      data.DeleteText,
			DeleteActionBase: "/contacts",
			Rows:             contactRows(data.Contacts),
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func contactFields(data ContactsPageData) []dashboardblocks.ContactField {
	return []dashboardblocks.ContactField{
		{Label: data.NameLabel, Name: "name", Type: "text", Required: true},
		{Label: data.EmailLabel, Name: "email", Type: "email", Required: true},
		{Label: data.CompanyLabel, Name: "company", Type: "text"},
	}
}

func contactRows(rows []ContactRow) []dashboardblocks.ContactRow {
	out := make([]dashboardblocks.ContactRow, 0, len(rows))
	for _, row := range rows {
		out = append(out, dashboardblocks.ContactRow{
			ID:        row.ID,
			Name:      row.Name,
			Email:     row.Email,
			Company:   row.Company,
			CreatedAt: row.CreatedAt,
		})
	}
	return out
}

var _ = templruntime.GeneratedTemplate
