// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import storefrontblocks "github.com/fastygo/blocks/storefront"

func StorefrontPage(data Page) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = storefrontblocks.StorefrontPage(storefrontProps(data)).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func storefrontProps(data Page) storefrontblocks.StorefrontPageProps {
	return storefrontblocks.StorefrontPageProps{
		Hero:        heroProps(data.Hero),
		Categories:  categoryCards(data.Categories),
		Collections: collectionCards(data.Collections),
		Benefits:    benefitItems(data.Benefits),
		Product:     productPreview(data.Product),
		Rail:        railProps(data.Rail),
		Footer:      footerProps(data.Footer),
	}
}

func heroProps(hero Hero) storefrontblocks.HeroProps {
	return storefrontblocks.HeroProps{
		Kicker:       hero.Kicker,
		Title:        hero.Title,
		Description:  hero.Description,
		Primary:      action(hero.Primary),
		SlideCurrent: hero.SlideCurrent,
		SlideTotal:   hero.SlideTotal,
		Previous:     action(hero.Previous),
		Next:         action(hero.Next),
		Image: storefrontblocks.ImageRef{
			Src: storefrontblocks.PlaceholderHeroInterior,
			Alt: hero.Image.Alt,
		},
	}
}

func categoryCards(items []Category) []storefrontblocks.CategoryCard {
	out := make([]storefrontblocks.CategoryCard, 0, len(items))
	placeholders := []string{
		storefrontblocks.PlaceholderSofa,
		storefrontblocks.PlaceholderTable,
		storefrontblocks.PlaceholderLamp,
		storefrontblocks.PlaceholderVase,
	}
	for i, item := range items {
		out = append(out, storefrontblocks.CategoryCard{
			Title: item.Title,
			Count: item.Count,
			Href:  item.Href,
			Image: storefrontblocks.ImageRef{
				Src: placeholders[i%len(placeholders)],
				Alt: item.Image.Alt,
			},
		})
	}
	return out
}

func collectionCards(items []Collection) []storefrontblocks.CollectionCard {
	out := make([]storefrontblocks.CollectionCard, 0, len(items))
	placeholders := []string{
		storefrontblocks.PlaceholderChair,
		storefrontblocks.PlaceholderHeroInterior,
		storefrontblocks.PlaceholderTable,
	}
	for i, item := range items {
		out = append(out, storefrontblocks.CollectionCard{
			Label:       item.Label,
			Title:       item.Title,
			Description: item.Description,
			Href:        item.Href,
			Image: storefrontblocks.ImageRef{
				Src: placeholders[i%len(placeholders)],
				Alt: item.Image.Alt,
			},
		})
	}
	return out
}

func benefitItems(items []Benefit) []storefrontblocks.BenefitItem {
	out := make([]storefrontblocks.BenefitItem, 0, len(items))
	for _, item := range items {
		out = append(out, storefrontblocks.BenefitItem{
			Icon:        item.Icon,
			Title:       item.Title,
			Description: item.Description,
		})
	}
	return out
}

func productPreview(product Product) storefrontblocks.ProductPreview {
	return storefrontblocks.ProductPreview{
		Badge:          product.Badge,
		Name:           product.Name,
		Price:          product.Price,
		OldPrice:       product.OldPrice,
		Description:    product.Description,
		Gallery:        galleryImages(product.Gallery),
		MainImage:      imageRef(product.MainImage, storefrontblocks.PlaceholderProduct),
		ColorsLabel:    product.ColorsLabel,
		Colors:         swatchItems(product.Colors),
		SelectedColor:  product.SelectedColor,
		Quantity:       quantityProps(product.Quantity),
		AddAction:      action(product.AddAction),
		FavoriteAction: action(product.FavoriteAction),
		Details:        detailRows(product.Details),
	}
}

func railProps(rail Rail) storefrontblocks.RailProps {
	return storefrontblocks.RailProps{
		Cart:        cartSummary(rail.Cart),
		Filter:      filterPanel(rail.Filter),
		Inspiration: inspirationCard(rail.Inspiration),
		Newsletter: storefrontblocks.NewsletterProps{
			Title:       rail.Newsletter.Title,
			Description: rail.Newsletter.Description,
			Placeholder: rail.Newsletter.Placeholder,
			SubmitLabel: rail.Newsletter.SubmitLabel,
		},
		Socials: actions(rail.Socials),
	}
}

func cartSummary(cart Cart) storefrontblocks.CartSummary {
	return storefrontblocks.CartSummary{
		Title:          cart.Title,
		CountLabel:     cart.CountLabel,
		Items:          cartItems(cart.Items),
		TotalLabel:     cart.TotalLabel,
		Total:          cart.Total,
		CheckoutAction: action(cart.CheckoutAction),
		ViewCartAction: action(cart.ViewCartAction),
	}
}

func cartItems(items []CartItem) []storefrontblocks.CartItem {
	out := make([]storefrontblocks.CartItem, 0, len(items))
	placeholders := []string{storefrontblocks.PlaceholderSofa, storefrontblocks.PlaceholderTable}
	for i, item := range items {
		out = append(out, storefrontblocks.CartItem{
			Title:    item.Title,
			Subtitle: item.Subtitle,
			Price:    item.Price,
			Image:    imageRef(item.Image, placeholders[i%len(placeholders)]),
		})
	}
	return out
}

func filterPanel(filter Filter) storefrontblocks.FilterPanel {
	return storefrontblocks.FilterPanel{
		Title:         filter.Title,
		ResetLabel:    filter.ResetLabel,
		CategoryLabel: filter.CategoryLabel,
		CategoryValue: filter.CategoryValue,
		MaterialLabel: filter.MaterialLabel,
		Materials:     swatchItems(filter.Materials),
		Price: storefrontblocks.PriceRange{
			Label:    filter.Price.Label,
			MinLabel: filter.Price.MinLabel,
			MaxLabel: filter.Price.MaxLabel,
			Value:    filter.Price.Value,
		},
		ColorLabel:    filter.ColorLabel,
		Colors:        swatchItems(filter.Colors),
		ShowAllAction: action(filter.ShowAllAction),
	}
}

func inspirationCard(inspiration Inspiration) storefrontblocks.InspirationCard {
	return storefrontblocks.InspirationCard{
		Title:       inspiration.Title,
		Description: inspiration.Description,
		Action:      action(inspiration.Action),
		Image:       imageRef(inspiration.Image, storefrontblocks.PlaceholderVase),
	}
}

func footerProps(footer Footer) storefrontblocks.FooterProps {
	return storefrontblocks.FooterProps{
		BrandName: footer.BrandName,
		Copyright: footer.Copyright,
		Groups:    footerGroups(footer.Groups),
	}
}

func footerGroups(groups []FooterGroup) []storefrontblocks.FooterGroup {
	out := make([]storefrontblocks.FooterGroup, 0, len(groups))
	for _, group := range groups {
		out = append(out, storefrontblocks.FooterGroup{
			Title: group.Title,
			Links: actions(group.Links),
		})
	}
	return out
}

func galleryImages(images []Image) []storefrontblocks.ImageRef {
	out := make([]storefrontblocks.ImageRef, 0, len(images))
	for _, image := range images {
		out = append(out, imageRef(image, storefrontblocks.PlaceholderProduct))
	}
	return out
}

func imageRef(image Image, src string) storefrontblocks.ImageRef {
	return storefrontblocks.ImageRef{Src: src, Alt: image.Alt}
}

func swatchItems(items []Swatch) []storefrontblocks.SwatchItem {
	out := make([]storefrontblocks.SwatchItem, 0, len(items))
	for _, item := range items {
		out = append(out, storefrontblocks.SwatchItem{
			Label:    item.Label,
			Value:    item.Value,
			Class:    item.Class,
			Selected: item.Selected,
		})
	}
	return out
}

func quantityProps(quantity Quantity) storefrontblocks.QuantityProps {
	return storefrontblocks.QuantityProps{
		Label:      quantity.Label,
		Value:      quantity.Value,
		MinusLabel: quantity.MinusLabel,
		PlusLabel:  quantity.PlusLabel,
	}
}

func detailRows(rows []Detail) []storefrontblocks.DetailRow {
	out := make([]storefrontblocks.DetailRow, 0, len(rows))
	for _, row := range rows {
		out = append(out, storefrontblocks.DetailRow{Label: row.Label, Value: row.Value})
	}
	return out
}

func actions(items []Action) []storefrontblocks.Action {
	out := make([]storefrontblocks.Action, 0, len(items))
	for _, item := range items {
		out = append(out, action(item))
	}
	return out
}

func action(item Action) storefrontblocks.Action {
	return storefrontblocks.Action{
		Label:     item.Label,
		Href:      item.Href,
		AriaLabel: item.AriaLabel,
	}
}

var _ = templruntime.GeneratedTemplate
