services:
  docs:
    build:
      context: .
      dockerfile: Dockerfile.docs
    container_name: ${COMPOSE_CONTAINER_NAME:-docs-paas}
    environment:
      APP_BIND: "0.0.0.0:80"
      APP_STATIC_DIR: "static"
    expose:
      - "80"
    restart: unless-stopped
