// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package partials

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/fastygo/elements/navigation"
	"github.com/fastygo/elements/toggles"
	"github.com/fastygo/framework/pkg/app"
	"github.com/fastygo/framework/pkg/web/view"
)

func HeaderActions(language view.LanguageToggleData, navItems []app.NavItem) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = navigation.HeaderNav(navigation.HeaderNavProps{
			Items: headerNavigationItems(navItems),
			Label: "Main navigation",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = toggles.HeaderLanguageToggle(toggles.HeaderLanguageToggleProps{
			ContainerClass: "ui-header-language",
			Toggle: toggles.LanguageToggleProps{
				ID:               "docs-language-toggle",
				Class:            "ui-header-action-btn",
				Href:             language.NextHref,
				DefaultLocale:    language.DefaultLocale,
				CurrentLocale:    language.CurrentLocale,
				CurrentLabel:     language.CurrentLabel,
				NextLocale:       language.NextLocale,
				NextLabel:        language.NextLabel,
				AvailableLocales: language.AvailableLocales,
				EnhanceWithJS:    language.EnhanceWithJS,
				SPATarget:        language.SPATarget,
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func headerNavigationItems(items []app.NavItem) []navigation.NavItem {
	out := make([]navigation.NavItem, 0, len(items))
	for _, item := range items {
		out = append(out, navigation.NavItem{
			Label: item.Label,
			Href:  item.Path,
		})
	}
	return out
}

var _ = templruntime.GeneratedTemplate
