// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strings"

	"github.com/fastygo/blocks/marketing"
	"github.com/fastygo/elements/toggles"
	ui8layout "github.com/fastygo/ui8kit/layout"
)

// Page is the data model rendered by Landing.
type Page struct {
	BrandName                string
	Lang                     string
	Tagline                  string
	Title                    string
	Subtitle                 string
	PrimaryCTA               string
	PrimaryHref              string
	Features                 []FeatureItem
	FooterText               string
	ThemeLabel               string
	ThemeDarkLabel           string
	ThemeLightLabel          string
	LanguageCurrentLocale    string
	LanguageCurrentLabel     string
	LanguageNextLocale       string
	LanguageNextLabel        string
	LanguageDefaultLocale    string
	LanguageAvailableLocales string
	LanguageNextHref         string
}

type FeatureItem struct {
	Title       string
	Description string
	Icon        string
}

func Landing(p Page) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = marketing.LandingPage(marketing.LandingPageProps{
				Classes: marketing.LandingPageClasses{
					Page: "landing-page",
				},
				Hero: marketing.HeroProps{
					Kicker:   p.Tagline,
					Title:    p.Title,
					Subtitle: p.Subtitle,
					PrimaryAction: marketing.Action{
						Label:  p.PrimaryCTA,
						Href:   p.PrimaryHref,
						NewTab: true,
					},
					Classes: marketing.HeroClasses{
						Section:  "landing-hero",
						Kicker:   "landing-kicker",
						Title:    "landing-title",
						Subtitle: "landing-subtitle",
						Actions:  "landing-cta-row",
						Action:   "landing-cta",
					},
				},
				Features: marketing.FeatureGridProps{
					Items: landingFeatures(p.Features),
					Classes: marketing.FeatureGridClasses{
						Section:     "landing-features",
						Card:        "landing-feature",
						Title:       "landing-feature-title",
						Description: "landing-feature-description",
					},
				},
				Footer: marketing.FooterProps{
					Text: p.FooterText,
					Classes: marketing.FooterClasses{
						Footer: "landing-footer",
					},
				},
			}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = ui8layout.Shell(ui8layout.ShellProps{
			Title:          p.Title,
			Lang:           p.Lang,
			BrandName:      p.BrandName,
			MarketingShell: true,
			Active:         "/",
			HeadExtra:      headExtra(),
			HeaderExtra:    landingLanguageToggle(p),
			ThemeToggle: ui8layout.ThemeToggleProps{
				Label:              p.ThemeLabel,
				SwitchToDarkLabel:  p.ThemeDarkLabel,
				SwitchToLightLabel: p.ThemeLightLabel,
			},
			ThemeToggleComponent: toggles.DarkModeToggle(toggles.DarkModeToggleProps{
				Label:              p.ThemeLabel,
				SwitchToDarkLabel:  p.ThemeDarkLabel,
				SwitchToLightLabel: p.ThemeLightLabel,
			}),
		}).Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func landingFeatures(features []FeatureItem) []marketing.FeatureItem {
	items := make([]marketing.FeatureItem, 0, len(features))
	for _, feature := range features {
		items = append(items, marketing.FeatureItem{
			Title:       feature.Title,
			Description: feature.Description,
			Icon:        feature.Icon,
		})
	}
	return items
}

func landingLanguageToggle(p Page) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = toggles.HeaderLanguageToggle(toggles.HeaderLanguageToggleProps{
			Toggle: toggles.LanguageToggleProps{
				ID:               "landing-language-toggle",
				Class:            "ui-header-action-btn",
				Href:             p.LanguageNextHref,
				DefaultLocale:    p.LanguageDefaultLocale,
				CurrentLocale:    p.LanguageCurrentLocale,
				CurrentLabel:     p.LanguageCurrentLabel,
				NextLocale:       p.LanguageNextLocale,
				NextLabel:        p.LanguageNextLabel,
				AvailableLocales: splitLocales(p.LanguageAvailableLocales),
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func headExtra() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		return nil
	})
}

func splitLocales(value string) []string {
	if value == "" {
		return nil
	}
	return strings.Split(value, ",")
}

var _ = templruntime.GeneratedTemplate
