// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	ui "github.com/fastygo/ui8kit/ui"
)

func WelcomePage(data WelcomePageData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"web-page\"><section class=\"web-hero\"><div class=\"web-hero-content\"><p class=\"web-hero-kicker\">Framework</p>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ui.Title(ui.TitleProps{Class: "web-hero-title"}, data.Title).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "<p class=\"web-hero-description\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(data.Description)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `internal/site/web/views/welcome.templ`, Line: 13, Col: 54}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</p><div class=\"web-hero-actions\"><a class=\"web-hero-cta web-hero-cta-primary\" href=\"https://github.com/fastygo/framework\" target=\"_blank\" rel=\"noopener noreferrer\">Github</a> <a class=\"web-hero-cta web-hero-cta-secondary\" href=\"https://docs.fastygo.ru\" target=\"_blank\" rel=\"noopener noreferrer\">Docs</a></div></div></section><div class=\"web-content-card\"><div class=\"web-hero-feature-grid\"><article class=\"web-hero-feature-card\"><h3 class=\"web-hero-feature-card-title\">Modular</h3><p>Feature modules split presentation, application logic, and infrastructure adapters.</p></article><article class=\"web-hero-feature-card\"><h3 class=\"web-hero-feature-card-title\">Fast bootstrap</h3><p>Clean layered foundation with ready-made CQRS pipeline and middleware stack.</p></article><article class=\"web-hero-feature-card\"><h3 class=\"web-hero-feature-card-title\">Production ready</h3><p>Server-side rendering, structured logs, and built-in observability-friendly boundaries.</p></article></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
