// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package views

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/fastygo/blocks/editorial"

func PostList(data PostListData) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = editorial.PostList(editorial.PostListProps{
			Title:       data.Title,
			Description: data.Description,
			Posts:       editorialPostListItems(data.Posts),
			Classes: editorial.PostListClasses{
				Page:        "blog-page",
				Header:      "blog-page-header",
				Title:       "blog-page-title",
				Description: "blog-page-description",
				List:        "blog-post-list",
				Card:        "blog-post-card",
				CardTitle:   "blog-post-card-title",
				CardSummary: "blog-post-card-summary",
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

func editorialPostListItems(posts []PostListItem) []editorial.PostListItem {
	items := make([]editorial.PostListItem, 0, len(posts))
	for _, post := range posts {
		items = append(items, editorial.PostListItem{
			Title:   post.Title,
			Summary: post.Summary,
			Href:    "/posts/" + post.Slug,
		})
	}
	return items
}

var _ = templruntime.GeneratedTemplate
